#
# Makefile for VL library
#

NAME        =   vl

SRCS		=	LibVLd.cc LibVLf.cc LibVLfd.cc VLInstantiate.cc Basics.cc

INC_DIRS		=	-I../include

BUILD_DBG_FLAGS	= 	-DCL_CHECKING

default: install install.dbg

include ../makefiles/lib.mf

DEST = ..
